[build]
  command = "pnpm run build"
  publish = "dist"

[build.environment]
  VITE_API_TARGET = "https://site.monsd.com/api"

[[redirects]]
  from = "/api/*"
  to = "https://site.monsd.com/api/:splat"
  status = 200
  force = true